doctrine:
  orm:
    mappings:
      AcMarche\Patrimoine:
        is_bundle: false
        dir: '%kernel.project_dir%/src/AcMarche/Patrimoine/src/Entity'
        prefix: 'AcMarche\Patrimoine'
        alias: AcMarchePatrimoine
