twig:
  form_themes: ['bootstrap_5_layout.html.twig']
  paths:
    '%kernel.project_dir%/src/AcMarche/Patrimoine/templates': AcMarchePatrimoine
  globals:
    g_latitude: "%env(PATRIMOINE_LATITUDE)%"
    g_longitude: "%env(PATRIMOINE_LONGITUDE)%"
